emulator/frontend_emulator/view_all_comment_emulator_DOC/blueprint.py
#!/usr/bin/env python3
# -*- 	coding: utf-8 -*-


from flask import request
from flask import jsonify
from flask import Blueprint
from flask import render_template
from backend_emulator.working_with_JSON_files.read_in_json import ReadsJson
from backend_emulator.get_requests.get_requests_comment_JSON import GetCommentJson


view_all_comment_emulator_DOC = Blueprint("view_all_comment_emulator_DOC", __name__, template_folder="templates")

@view_all_comment_emulator_DOC.route("/", methods=["GET", "POST"])
def index():
    data_json = ReadsJson(name_file="protocol.json").main()

    if data_json is not False:
        list_key_ticket = list(data_json.keys())

        if request.method == "GET":
            return render_template("view_all_comment_emulator_DOC/index.html", drop_down_list=list_key_ticket)

        if request.method == "POST":
            key_id = request.form["drop_down"]
            return jsonify(GetCommentJson(data_json, key_id).main())

    else:
        return render_template("error_404/index.html"), 404

emulator/frontend_emulator/view_all_comment_emulator_DOC/templates/error_404/index.html
{% extends 'base.html' %}

{% block title %}
    view_all_comment_emulator_DOC
{% endblock %}

{% block content_title %}
    view_all_comment_emulator_DOC
{% endblock %}

{% block content %}
  <h1>404 Page not found</h1>
{% endblock %}

emulator/frontend_emulator/view_all_comment_emulator_DOC/templates/view_all_comment_emulator_DOC/index.html
{% extends 'base.html' %}

{% block title %}
    view_all_comment_emulator_DOC
{% endblock %}

{% block content_title %}
    view_all_comment_emulator_DOC
{% endblock %}

{% block content %}
<div class="form">
    <form method="POST" action="{{ url_for('view_all_comment_emulator_DOC.index' )}}">
        <label for="key_id">Выберите ключ:</label>

        <select id="drop_down" name="drop_down">
            {% for option in drop_down_list %}
                <option value="{{ option }}">{{ option }}</option>
            {% endfor %}
        </select><br><br>

        <button type="submit" class="btn btn-warning btn-lg">submit</button>
{% endblock %}