main_app/Zammad_Connect/frontend/create_ticket/blueprint.py
#!/usr/bin/env python3
# -*- 	coding: utf-8 -*-


from flask import request
from flask import Blueprint
from flask import render_template
from Zammad_Connect.zammad_api.create_ticket import TicketCreate


create_ticket = Blueprint("create_ticket", __name__, template_folder="templates")

@create_ticket.route("/", methods=["GET", "POST"])
def index():
    if request.method == "POST":
        title = request.form["title"]
        group = request.form["group"]
        customer = request.form["customer"]
        article_subject = request.form["article_subject"]
        article_body = request.form["article_body"]
        article_type = request.form["article_type"]
        article_internal = request.form["article_internal"]

        dict = {
                    "title": title,
                    "group": group,
                    "customer": customer,
                    "article_subject": article_subject,
                    "article_body": article_body,
                    "article_type": article_type,
                    "article_internal": article_internal
        }

        TicketCreate(dict, data_from_web=True).main()

    return render_template("create_ticket/index.html")

main_app/Zammad_Connect/frontend/get_ticket/blueprint.py
#!/usr/bin/env python3
# -*- 	coding: utf-8 -*-


import requests
from flask import request
from flask import Blueprint
from flask import render_template
from Zammad_Connect.zammad_api.get_ticket import TicketArticles


get_ticket = Blueprint("get_ticket", __name__, template_folder="templates")

@get_ticket.route("/", methods=["GET", "POST"])
def index():
    if request.method == "POST":

        try:
            ticket_number = int(request.form["ticket_number"])
            ticket, ticket_articles = TicketArticles(ticket_number).main()

            return render_template("completed_ticket/index.html",  number_ticket=ticket, t_a=ticket_articles)

        except ValueError:
            return render_template("value_error_only_numbers/index.html")

        except requests.exceptions.HTTPError:
            return render_template("value_error_ticket_not_found/index.html")

    return render_template("get_ticket/index.html")

main_app/Zammad_Connect/frontend/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="
    sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>

        {% block title %}

        {% endblock %} | Flask app

    </title>
</head>
<body>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="{{ url_for('index') }}">Home page</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('create_ticket.index') }}">create_ticket</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('get_ticket.index') }}">get_ticket</a>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
          </li>
        </ul>
        <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
      </div>
    </nav>

    <div class="container">
        <div class="row">
            <h1>
                {% block content_title %}

                {% endblock %}
            </h1>
        </div>
            <h3>
                {% block content %}

                {% endblock %}
            </h3>
    </div>

</body>
</html>

main_app/Zammad_Connect/frontend/templates/index.html
{% extends 'base.html' %}

{% block title %}
    Index page
{% endblock %}

{% block content_title %}
    Home page
{% endblock %}

{% block content %}
    Test
{% endblock %}