emulator/frontend_emulator/add_a_comment/blueprint.py
#!/usr/bin/env python3
# -*- 	coding: utf-8 -*-


from flask import request
from flask import Blueprint
from flask import render_template
from backend_emulator.date_time.return_date_time import date_time
from backend_emulator.working_with_JSON_files.read_in_json import ReadsJson
from backend_emulator.working_with_data_add_comment.work_data import WorkDataAddComment


add_comment = Blueprint("add_comment", __name__, template_folder="templates")

@add_comment.route("/", methods=["GET", "POST"])
def index():
    data_json = ReadsJson(name_file="incidents.json").main()

    if data_json is not False:
        list_key_ticket = list(data_json.keys())

        if request.method == "POST":
            value = request.form["drop_down"]
            commit = request.form["commit"]
            author = request.form["author"]

            dict_data = {
                    value: [
                            {
                                    "author": author,
                                    "commit": commit,
                                    "data": date_time()
                            }
                    ]
            }

            WorkDataAddComment(dict_data).main()

            return render_template("add_comment/index.html", drop_down_list=list_key_ticket)

        if request.method == "GET":
            return render_template("add_comment/index.html", drop_down_list=list_key_ticket)

    else:
        return render_template("no_ticket/index.html", data="Нет тикетов!")

emulator/frontend_emulator/add_attachment/blueprint.py
#!/usr/bin/env python3
# -*- 	coding: utf-8 -*-

from flask import request, Blueprint, render_template
from backend_emulator.working_with_JSON_files.read_in_json import ReadsJson
from backend_emulator.attachment_processing.file_proccessing import FileProccessing
from backend_emulator.attachment_processing.attachment_handler import AttachmentHandler

add_attachment = Blueprint("add_attachment", __name__, template_folder="templates")


@add_attachment.route("/", methods=["GET", "POST"])
def index():
    data_json = ReadsJson(name_file="incidents.json").main()

    if data_json is not False:
        list_key_ticket = list(data_json.keys())

        if request.method == "GET":
                return render_template("add_attachment/index.html", drop_down_list=list_key_ticket)

        if request.method == "POST":
            if 'files[]' not in request.files:
                return 'No files attached', 400

            value = request.form["drop_down"]
            files = request.files.getlist('files[]')

            if value in list_key_ticket:
                data = {
                    'action': 'getAttachToken',
                    'drop_down': value,
                    'filename': 'Обращение'
                }

                for file in files:
                    AttachmentHandler(data, file).main()

            else:
                return "Incident doesn't exist"

            return render_template("add_attachment/index.html", drop_down_list=list_key_ticket)

    else:
        return render_template("404/index.html", data="Нет тикетов!")


@add_attachment.route('/<attach_token>/attachments', methods=["POST"])
def attach_attachment(attach_token):
    file = request.files['file']
    header = request.headers['Content-Disposition']
    result = FileProccessing(file, attach_token, header).main()
    return result

emulator/frontend_emulator/get_token_attachment_DOC/blueprint.py
#!/usr/bin/env python3
# -*- 	coding: utf-8 -*-


from flask import request
from flask import jsonify
from flask import Blueprint
from flask import render_template
from backend_emulator.working_with_JSON_files.read_in_json import ReadsJson
from backend_emulator.get_requests.get_requests_token_attachment import GetTokenAttachment


get_token_attachment_DOC = Blueprint("get_token_attachment_DOC", __name__, template_folder="templates")

@get_token_attachment_DOC.route("/", methods=["GET", "POST"])
def index():
    data_json = ReadsJson(name_file="incidents.json").main()

    if data_json is False:
        return render_template("no_ticket_for_token_attacment/index.html", data="НЕТ СОЗДАННЫХ ЗАЯВОК!")

    else:
        list_key_ticket = list(data_json.keys())

        if request.method == "POST":
            action = request.form["action"]
            key = request.form["drop_down"]
            filename = request.form["filename"]

            dict_data = {
                            key: {
                                    "ditMFSMAPI": {
                                                    "Action": action,
                                                    "Key": key,
                                                    "Filename": filename
                                    }
                            }
            }

            GetTokenAttachment(key, dict_data).main()

            return jsonify(ReadsJson(name_file="token_attachment.json").main())

        if request.method == "GET":
            return render_template("get_token_attachment_DOC/index.html", drop_down_list=list_key_ticket)

emulator/frontend_emulator/view_all_ticket_emulator_DOC/blueprint.py
#!/usr/bin/env python3
# -*- 	coding: utf-8 -*-


from flask import jsonify
from flask import Blueprint
from flask import render_template
from backend_emulator.get_requests.get_requests_ticket_JSON import GetJson
from backend_emulator.working_with_JSON_files.read_in_json import ReadsJson


view_all_ticket_emulator_DOC = Blueprint("view_all_ticket_emulator_DOC", __name__, template_folder="templates")

@view_all_ticket_emulator_DOC.route("/")
def index():
    data_json = ReadsJson(name_file="incidents.json").main()

    if data_json is False:
        return render_template("view_all_ticket_emulator_DOC/index.html", data="НЕТ СОЗДАННЫХ ЗАЯВОК!")
    else:
        return jsonify(GetJson(data_json).main())

emulator/frontend_emulator/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="
    sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>

        {% block title %}

        {% endblock %} | Flask app

    </title>
</head>
<body>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="{{ url_for('index') }}">Home page</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">

        <ul class="navbar-nav mr-auto">

          <li class="nav-item">
              <a class="nav-link" href="{{ url_for('create_ticket_emulator.index') }}">create_ticket_emulator</a>
          </li>

          <li class="nav-item">
              <a class="nav-link" href="{{ url_for('view_all_ticket_emulator_DOC.index') }}">view_all_ticket_emulator_DOC</a>
          </li>

          <li class="nav-item">
              <a class="nav-link" href="{{ url_for('add_comment.index') }}">add_comment</a>
          </li>

          <li class="nav-item">
              <a class="nav-link" href="{{ url_for('view_all_comment_emulator_DOC.index') }}">view_all_comment_emulator_DOC</a>
          </li>

          <li class="nav-item">
              <a class="nav-link" href="{{ url_for('get_token_attachment_DOC.index') }}">get_token_attachment_DOC</a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('add_attachment.index') }}">add_attachment</a>
          </li>

        </ul>

        <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
      </div>
    </nav>

    <div class="container">
        <div class="row">
            <h1>
                {% block content_title %}

                {% endblock %}
            </h1>
        </div>
            <h3>
                {% block content %}

                {% endblock %}
            </h3>
    </div>

</body>
</html>

emulator/frontend_emulator/templates/index.html
{% extends 'base.html' %}

{% block title %}
    Index page
{% endblock %}

{% block content_title %}
    Emulator
{% endblock %}

{% block content %}
    This is emulator
{% endblock %}